version: '3.5'
services:
  adminer:
    container_name: socialup_adminer
    image: adminer:latest
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - .:/application:cached

  redisui:
    container_name: socialup_redisui
    image: rediscommander/redis-commander:latest
    ports:
      - 8081:8081
    env_file: .env