version: '3.5'
services:
  application:
    container_name: socialup_application
    command: 'true'
    build: .
    env_file: .env.production
    working_dir: /application
    stdin_open: true
    tty: true
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web

  admin_bot:
    container_name: socialup_admin_bot
    build: .
    command: bash -c "ruby ./bin/admin_bot"
    env_file: .env.production
    working_dir: /application
    stdin_open: true
    tty: true
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web
    restart: always

  pdr_bot:
    container_name: socialup_pdr_bot
    build: .
    command: bash -c "ruby ./bin/pdr_bot"
    env_file: .env.production
    working_dir: /application
    stdin_open: true
    tty: true
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web
    restart: always

  jenia_bot:
    container_name: socialup_jenia_bot
    build: .
    command: bash -c "ruby ./bin/jenia_bot"
    env_file: .env.production
    working_dir: /application
    stdin_open: true
    tty: true
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web
    restart: always

  example_bot:
    container_name: socialup_example_bot
    build: .
    command: bash -c "ruby ./bin/example_bot"
    env_file: .env.production
    working_dir: /application
    stdin_open: true
    tty: true
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web
    restart: always

  caddy:
    container_name: socialup_caddy
    image: abiosoft/caddy:0.10.14
    env_file: .env.production
    volumes:
      - ./docker-configs/caddy/Caddyfile:/etc/Caddyfile
      - caddy-config:/root/.caddy
    ports:
      - 80:80
      - 443:443
    networks:
      - default
      - web
    environment:
      - ACME_AGREE=true
    restart: always

  dozzle:
    container_name: socialup_dozzle
    image: amir20/dozzle:latest
    environment:
      - DOZZLE_TAILSIZE=300
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8082:8080
    networks:
      - default
      - web
    restart: always

  sidekiq:
    container_name: socialup_sidekiq
    build: .
    command: bash -c "bundle exec sidekiq -e development -r ./config/boot.rb -C ./config/sidekiq.yml"
    env_file: .env.production
    working_dir: /application
    stdin_open: true
    tty: true
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    depends_on:
      - database
      - redis
    networks:
      - default
      - web
    restart: always

  sidekiqui:
    container_name: socialup_sidekiqui
    build: .
    command: bundle exec rackup apps/sidekiqui/config.ru -p 9393 --server=webrick --host 0.0.0.0
    env_file: .env.production
    working_dir: /application
    volumes:
      - .:/application:cached
      - bundle-cache:/usr/local/bundle:cached
    ports:
      - 9393:9393
    depends_on:
      - sidekiq
    networks:
      - default
      - web
    restart: always

  database:
    container_name: socialup_database
    image: postgres:10.3-alpine
    command: postgres -c 'max_connections=150'
    ports:
      - 5433:5432
    env_file: .env.production
    volumes:
      - .:/application:cached
      - db-data:/var/lib/postgresql/data:cached
    restart: always

  pgbackup:
    container_name: socialup_pgbackup
    image: prodrigestivill/postgres-backup-local
    env_file: .env.production
    environment:
      SCHEDULE: '@daily'
    volumes:
      - ./backups:/backups
    depends_on:
      - database
    restart: always
    networks:
      - default
      - web

  adminer:
    container_name: socialup_adminer
    image: adminer:latest
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    env_file: .env.production
    volumes:
      - .:/application:cached
    restart: always

  redis:
    container_name: socialup_redis
    image: redis:4.0-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    env_file: .env.production
    ports:
      - 6380:6379
    volumes:
      - redis-storage:/data:cached
      - ./docker-configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    restart: always

  redisui:
    container_name: socialup_redisui
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    ports:
      - 8081:8081
    env_file: .env.production
    restart: always

volumes:
  db-data: null
  caddy-config: null
  bundle-cache: null
  redis-storage: null

networks:
  default:
  web: