---
# Set desired concurrency here. By default 1
:concurrency: 1
:logfile: log/sidekiq.log

:queues:
  - critical
  - default
  - low

:schedule:
  # Specify your worker schedule here

  # MyBot::DeleteOldMessagesWorker:
  #   cron: '0 0 1 * *'   # Runs every month
  #   class: MyBot::DeleteOldMessagesWorker
  #   description: 'This job deletes old messages for MyBot'
